################################
#   MoonLake Core API Plugin   #
#  By Month_Light Ver: 1.8-b4  #
################################

# 插件版本号: 此项请勿修改!
version: '1.8-b4'

# 数据包通道监听器
# 此项可设置是否开启这个功能
# 如果关闭则插件中的一些API功能将无法使用
# 例如: MoonLakePlayerJoinEvent
# PS: 此项是实时监听客户端与服务端的数据包交流
PacketChannelListener: false
