################################
#   MoonLake Core API Plugin   #
#  By Month_Light Ver: 1.8-a3  #
################################

# 插件版本号: 此项请勿修改!
version: '1.8-a3'

# 插件国际化的语言文件加载设置
# 详情可以查看插件目录 \MoonLake\languages\
# 内的语言文件, 如需要改变请自行修改
Language: 'zh_CN'