################################
#   MoonLake Core API Plugin   #
#  By Month_Light Ver: 1.8-b3  #
################################

# 插件版本号: 此项请勿修改!
version: '1.8-b3'

# 插件国际化的语言文件加载设置
# 详情可以查看插件目录 \MoonLake\languages\
# 内的语言文件, 如需要改变请自行修改
Language: 'zh_CN'

# 数据包通道监听器
# 此项可设置是否开启这个功能
# 如果关闭则插件中的一些API功能将无法使用
# 例如: MoonLakePlayerJoinEvent
# PS: 此项是实时监听客户端与服务端的数据包交流
PacketChannelListener: true